### ISSUE TITLE
multicore proc error for Windows 10

### ISSUE THREAD

**Issue by demanasta** [DSOlab/StrainTool#71]
**Describe the bug**
multi-threading mode not working on Windows 10

**To Reproduce**
1. run command  `.\StrainTensor.py -i <data_file> --x-grid-step 1 --y-grid-step 1 -g --multicore`
2. check for error 
```
Traceback (most recent call last):
  File "D:\gh_project\StrainTool\bin\StrainTensor.py", line 487, in <module>
    [ p.start() for p in [p1, p2, p3, p4]]
  File "D:\gh_project\StrainTool\bin\StrainTensor.py", line 487, in <listcomp>
    [ p.start() for p in [p1, p2, p3, p4]]
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object
PS D:\gh_project\StrainTool\bin> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python39\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "C:\Program Files\Python39\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Δεν επιτρέπεται η πρόσβαση
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python: 3.9.7
 - GMT: 6.x
 - StrainTool: v1.0-r1

**Comment by xanthospap** [comment]
Seems like a python3.x bug on windows!!
See [SO](https://stackoverflow.com/questions/65891898/python-multiprocessing-permissionerror-winerror-5-access-is-denied) and [this report](https://bugs.python.org/issue38263)

**Comment by demanasta** [comment]
Check this back on the next release
